### ISSUE TITLE
L/R axes aren't mapped yet for 3D pads

### ISSUE THREAD

**Issue by mistydemeo** [abrasive/saturn-pademu#7]
Right now, just the X and Y axes are mapped for the 3D pad. (Along with the probably unused Z axis.) Yabause defines the config like this: https://github.com/Yabause/yabause/blob/master/yabause/src/peripheral.c#L103-L111 https://github.com/Yabause/yabause/blob/master/yabause/src/qt/ui/UI3DControlPadSetting.cpp#L49-L50

Looks like they're (in Yabause's numbering) axes 3 and 4, where axes 1 and 2 are X and Y.

**Comment by mistydemeo** [comment]
Simply adding extra axes to `AnalogPad::AnalogPad` and bumping `data_size` doesn't seem to have appreciable effect, but I might be missing something.

**Comment by abrasive** [comment]
This needed more axis scaling; L/R now working (at least in Shining Force III, once I got past the incredibly long intro).

It's not quite complete though. The AnalogPad should emulate LT/RT digital buttons too. According to [this post](https://segaxtreme.net/threads/nights-analog-pad-data-format.17522/) they should turn on around 0x90 and off at about 0x56; I'm not sure how to implement this most neatly.

**Comment by abrasive** [comment]
Right, analog axis to digital control is implemented so that a mapping pair like
```
InputGamepad::add_axis_mapping(SDL_CONTROLLER_AXIS_TRIGGERLEFT, ctl, p1->get_control("Laxis"));
InputGamepad::add_axis_mapping(SDL_CONTROLLER_AXIS_TRIGGERLEFT, ctl, p1->get_control("LT"));
```
will do the needful.

**Comment by mistydemeo** [comment]
Thanks!

Something seems to be potentially acting up in games that use the analogue triggers - they don't register anything at all. No button presses or axes work. 3D pad games that only use the digital presses on the triggers work.

In testing, it doesn't seem to matter whether the analogue triggers are actually mapped, just whether the game expects to use them. For example, changing `client.cpp` to create a `new AnalogPad()` works to test this.

3D pad I tested that treat the triggers as digital, and work:
* Burning Rangers
* Nights

3D pad games I tested that treat the triggers as axes, and don't work:
* Galaxy Force II
* Outrun
* Willy Wombat

**Comment by mistydemeo** [comment]
...you know, I think it's my Saturn. It looks like it's happening with an original 3D pad.

**Comment by abrasive** [comment]
In that case, that is a really weird issue.

Contact problems are probably out because loss of any would break 
individual buttons or everything.

The same data goes over the wire to the SMPC regardless of tge 
application's request; the SMPC uses the data length provided by the 
peripheral. It is possible that Sega's app libraries do something odd with 
the analog pad reading though that interacts with eg. an aged capacitor or 
something.

The Padulator has debug output available - just cat /dev/ttyACM0. If the 
SMPC stops reading bytes while the padulator os still sending, it will 
signal an overrun.

It's also possible that the SMPC is somehow in a bad state and needs a full 
reset? (ie including backup battery) - last resort aort of thing.

You tried both ports too, I'm guessing.
